// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string package_name = "com.EugeneTanJianpeng.Virucide"; // <GPGSID>
        public const string achievement_beat_level_10 = "CgkI_Jmw1_sTEAIQAA"; // <GPGSID>
        public const string leaderboard_endless_explosions = "CgkI_Jmw1_sTEAIQCQ"; // <GPGSID>
        public const string leaderboard_infection = "CgkI_Jmw1_sTEAIQBQ"; // <GPGSID>
        public const string achievement_beat_level_50 = "CgkI_Jmw1_sTEAIQBA"; // <GPGSID>
        public const string leaderboard_anemia = "CgkI_Jmw1_sTEAIQBw"; // <GPGSID>
        public const string leaderboard_portal_pickle = "CgkI_Jmw1_sTEAIQCg"; // <GPGSID>
        public const string achievement_beat_level_40 = "CgkI_Jmw1_sTEAIQAg"; // <GPGSID>
        public const string leaderboard_spike_fall = "CgkI_Jmw1_sTEAIQCA"; // <GPGSID>
        public const string achievement_beat_level_30 = "CgkI_Jmw1_sTEAIQAw"; // <GPGSID>
        public const string leaderboard_perfect_aim = "CgkI_Jmw1_sTEAIQBg"; // <GPGSID>
        public const string achievement_beat_level_20 = "CgkI_Jmw1_sTEAIQAQ"; // <GPGSID>

}

